[project]
name = "llm-translator"
version = "0.0.1"
description = "A system for translating between human languages using an LLM"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "lxml>=6.0.0",
]

[dependency-groups]
dev = ["ruff"]